/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee_management_system;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Afzal computers
 */
public class Admin_Panel extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Panel
     */
    String empID=null;
    public Admin_Panel() {
        initComponents();
       
        loadTbl();
        Admntbl.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                btn_disable.setEnabled(true);
               empID=Admntbl.getValueAt(Admntbl.getSelectedRow(), 0).toString();
               txtfld_emp_name.setText(Admntbl.getValueAt(Admntbl.getSelectedRow(), 1).toString());
               txtfld_emp_lastname.setText(Admntbl.getValueAt(Admntbl.getSelectedRow(), 2).toString());
               txtfld_emp_address.setText(Admntbl.getValueAt(Admntbl.getSelectedRow(), 3).toString());
               txtfld_emp_salary.setText(Admntbl.getValueAt(Admntbl.getSelectedRow(), 4).toString());
               txtfld_Designation.setText(Admntbl.getValueAt(Admntbl.getSelectedRow(), 5).toString());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLbl1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_search = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jlbl6 = new javax.swing.JLabel();
        BT_update = new javax.swing.JButton();
        btn_disable = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Admntbl = new javax.swing.JTable();
        entrbtn = new javax.swing.JButton();
        lbl_EmpName = new javax.swing.JLabel();
        lbl_Empaddress = new javax.swing.JLabel();
        lbl_EmpLastname = new javax.swing.JLabel();
        lbl_Empsalary = new javax.swing.JLabel();
        lbl_EmpDesignation = new javax.swing.JLabel();
        txtfld_Designation = new javax.swing.JTextField();
        txtfld_emp_salary = new javax.swing.JTextField();
        txtfld_emp_lastname = new javax.swing.JTextField();
        txtfld_emp_address = new javax.swing.JTextField();
        txtfld_emp_name = new javax.swing.JTextField();
        txtfld_search = new javax.swing.JTextField();
        btn_refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee_management_system/image001.png"))); // NOI18N

        jLbl1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl1.setText("Admin Panel");

        lbl_search.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_search.setText("Search Employee:");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afzal computers\\Downloads\\e projects\\employee.png")); // NOI18N

        jlbl6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbl6.setText("EMPLOYEE MANAGEMENT SYSTEM");

        BT_update.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BT_update.setText("Update");
        BT_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_updateActionPerformed(evt);
            }
        });

        btn_disable.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_disable.setText("Disable");
        btn_disable.setDoubleBuffered(true);
        btn_disable.setEnabled(false);
        btn_disable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_disableActionPerformed(evt);
            }
        });

        Admntbl.setBorder(new javax.swing.border.MatteBorder(null));
        Admntbl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Admntbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Emp_ID", "Emp_Name", "Emp_Last name", "Emp_Address", "Emp_Salary", "Emp_Designation"
            }
        ));
        jScrollPane1.setViewportView(Admntbl);

        entrbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        entrbtn.setText("Enter");
        entrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrbtnActionPerformed(evt);
            }
        });

        lbl_EmpName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_EmpName.setText("Emp Name:");

        lbl_Empaddress.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_Empaddress.setText("Emp address:");

        lbl_EmpLastname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_EmpLastname.setText("Emp Last name:");

        lbl_Empsalary.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_Empsalary.setText("Emp Salary:");

        lbl_EmpDesignation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_EmpDesignation.setText("Emp Designation:");

        txtfld_Designation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtfld_Designation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld_DesignationActionPerformed(evt);
            }
        });

        txtfld_emp_salary.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtfld_emp_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld_emp_salaryActionPerformed(evt);
            }
        });

        txtfld_emp_lastname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtfld_emp_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld_emp_lastnameActionPerformed(evt);
            }
        });

        txtfld_emp_address.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtfld_emp_address.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld_emp_addressActionPerformed(evt);
            }
        });

        txtfld_emp_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtfld_emp_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld_emp_nameActionPerformed(evt);
            }
        });

        txtfld_search.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        btn_refresh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_refresh.setText("Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jlbl6)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(274, 274, 274)
                                .addComponent(jLbl1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 634, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_EmpLastname)
                                            .addComponent(lbl_EmpName)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(lbl_Empsalary))
                                            .addComponent(lbl_Empaddress))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtfld_emp_address)
                                            .addComponent(txtfld_emp_lastname)
                                            .addComponent(txtfld_emp_name)
                                            .addComponent(txtfld_emp_salary)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(lbl_EmpDesignation)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(txtfld_Designation))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(BT_update)
                                                .addGap(31, 31, 31)
                                                .addComponent(btn_disable)
                                                .addGap(21, 21, 21)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_refresh, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(85, 85, 85)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_search)
                        .addGap(18, 18, 18)
                        .addComponent(txtfld_search, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(entrbtn)
                        .addGap(161, 161, 161))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLbl1)
                        .addGap(32, 32, 32)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtfld_emp_name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_EmpName))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_EmpLastname)
                                    .addComponent(txtfld_emp_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtfld_emp_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_Empaddress))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_Empsalary)
                                    .addComponent(txtfld_emp_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_EmpDesignation)
                                    .addComponent(txtfld_Designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BT_update)
                                    .addComponent(btn_disable)
                                    .addComponent(btn_refresh))
                                .addGap(3, 3, 3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(jlbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_search)
                                    .addComponent(txtfld_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(entrbtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_updateActionPerformed
        try
        {
              Data dt=new Data();
       int upd8= dt.updateRecords(empID, txtfld_emp_name.getText(), txtfld_emp_lastname.getText(), txtfld_emp_address.getText(), txtfld_emp_salary.getText(), txtfld_Designation.getText());
        if (upd8>0) {
            
        
            JOptionPane.showMessageDialog(null, "Employee is Updated");
         
        } 
else
        {
          JOptionPane.showMessageDialog(null, "Employee is not Updated");  
        }
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e);  
        }
    }//GEN-LAST:event_BT_updateActionPerformed

    private void entrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrbtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_entrbtnActionPerformed

    private void txtfld_DesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld_DesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld_DesignationActionPerformed

    private void txtfld_emp_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld_emp_lastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld_emp_lastnameActionPerformed

    private void txtfld_emp_addressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld_emp_addressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld_emp_addressActionPerformed

    private void txtfld_emp_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld_emp_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld_emp_nameActionPerformed

    private void txtfld_emp_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld_emp_salaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld_emp_salaryActionPerformed

    private void btn_disableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_disableActionPerformed
  
   try
        {
              Data dt=new Data();
       int Dele= dt.DisableRecords( empID);
        if (Dele>0) {
            
        
            JOptionPane.showMessageDialog(null, "Employee is Disabled");
         
        } 
else
        {
          JOptionPane.showMessageDialog(null, "Employee is not Disabled");  
        }
        } 
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null,e);  
        }
    }//GEN-LAST:event_btn_disableActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
     try {
            ResultSet rst=new Data().getEmployees();
            DefaultTableModel model=(DefaultTableModel)Admntbl.getModel();
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{"ID","F Name","L Name","Address","Salary","Designation"});
            while (rst.next())
            {
                model.addRow(new Object[]{rst.getInt(1),rst.getString(2),rst.getString(3),rst.getString(4),rst.getString(5),rst.getString(6)});
            }
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_btn_refreshActionPerformed

   
    public void loadTbl()
    {
        try {
            ResultSet rst=new Data().getEmployees();
            DefaultTableModel model=(DefaultTableModel)Admntbl.getModel();
            model.setRowCount(0);
            model.setColumnIdentifiers(new Object[]{"ID","F Name","L Name","Address","Salary","Designation"});
            while (rst.next())
            {
                model.addRow(new Object[]{rst.getString(1),rst.getString(2),rst.getString(3),rst.getString(4),rst.getString(5),rst.getString(6)});
            }
        } catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, e);
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Admntbl;
    private javax.swing.JButton BT_update;
    private javax.swing.JButton btn_disable;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton entrbtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLbl1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlbl6;
    private javax.swing.JLabel lbl_EmpDesignation;
    private javax.swing.JLabel lbl_EmpLastname;
    private javax.swing.JLabel lbl_EmpName;
    private javax.swing.JLabel lbl_Empaddress;
    private javax.swing.JLabel lbl_Empsalary;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JTextField txtfld_Designation;
    private javax.swing.JTextField txtfld_emp_address;
    private javax.swing.JTextField txtfld_emp_lastname;
    private javax.swing.JTextField txtfld_emp_name;
    private javax.swing.JTextField txtfld_emp_salary;
    private javax.swing.JTextField txtfld_search;
    // End of variables declaration//GEN-END:variables
}
