package employee_management_system;

import javax.swing.JOptionPane;

public class Employee_Register extends javax.swing.JFrame {

    /**
     * Creates new form Employee_Register
     */
    public Employee_Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLbl16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jlbl6 = new javax.swing.JLabel();
        jLbl1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLbll4 = new javax.swing.JLabel();
        txtfld_name = new javax.swing.JTextField();
        jLbl5 = new javax.swing.JLabel();
        cmbbx_gender = new javax.swing.JComboBox<>();
        jLbl7 = new javax.swing.JLabel();
        txtfld_dob = new javax.swing.JTextField();
        jLbl8 = new javax.swing.JLabel();
        txtfld_age = new javax.swing.JTextField();
        jLbl9 = new javax.swing.JLabel();
        jLbl11 = new javax.swing.JLabel();
        txtfld_salary = new javax.swing.JTextField();
        jLbl13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLbl15 = new javax.swing.JLabel();
        txtfield_emailID = new javax.swing.JTextField();
        TxtFld_contactno = new javax.swing.JTextField();
        jLbl17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLbl19 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea_address = new javax.swing.JTextArea();
        Btn_submit = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtfld_lastname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        lbl_nicno = new javax.swing.JLabel();
        txtfld_nicno = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        pass_box = new javax.swing.JPasswordField();
        txtfiled_designation = new javax.swing.JTextField();

        jLbl16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLbl16.setText("Contact No:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee_management_system/image001.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("EMPLOYEE MANAGEMENT SYSTEM");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afzal computers\\Downloads\\e projects\\employee.png")); // NOI18N

        jlbl6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jlbl6.setText("EMPLOYEE MANAGEMENT SYSTEM");

        jLbl1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLbl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbl1.setText("Employee Registeration");

        jLbll4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLbll4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbll4.setText("Name:");

        txtfld_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtfld_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld_nameActionPerformed(evt);
            }
        });

        jLbl5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLbl5.setText("Gender:");

        cmbbx_gender.setEditable(true);
        cmbbx_gender.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbbx_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female" }));
        cmbbx_gender.setName("Select"); // NOI18N
        cmbbx_gender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbbx_genderActionPerformed(evt);
            }
        });

        jLbl7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLbl7.setText("Date of Birth:");

        txtfld_dob.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtfld_dob.setText("DD/MM/YY");
        txtfld_dob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld_dobActionPerformed(evt);
            }
        });

        jLbl8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLbl8.setText("Age:");

        txtfld_age.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtfld_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld_ageActionPerformed(evt);
            }
        });

        jLbl9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLbl9.setText("Designation:");

        jLbl11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLbl11.setText("Salary:");

        txtfld_salary.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtfld_salary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld_salaryActionPerformed(evt);
            }
        });

        jLbl13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLbl13.setText("Joined On:");

        jLbl15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLbl15.setText("Email Id:");

        txtfield_emailID.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        txtfield_emailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfield_emailIDActionPerformed(evt);
            }
        });

        TxtFld_contactno.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        TxtFld_contactno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFld_contactnoActionPerformed(evt);
            }
        });

        jLbl17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLbl17.setText("Contact Details:");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel18.setText("Contact No:");

        jLbl19.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLbl19.setText("Address:");

        textArea_address.setColumns(20);
        textArea_address.setRows(5);
        jScrollPane1.setViewportView(textArea_address);

        Btn_submit.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Btn_submit.setText("Submit");
        Btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_submitActionPerformed(evt);
            }
        });

        btn_reset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Last Name:");

        txtfld_lastname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtfld_lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfld_lastnameActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Password:");

        lbl_nicno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_nicno.setText("NIC No:");

        txtfld_nicno.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        pass_box.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtfiled_designation.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(449, 449, 449)
                .addComponent(Btn_submit)
                .addGap(31, 31, 31)
                .addComponent(btn_reset)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(226, 226, 226)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(jLbl1))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLbll4)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtfld_name, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLbl5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cmbbx_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLbl7)
                                            .addComponent(jLbl9)
                                            .addComponent(jLbl11))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtfld_dob, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtfld_salary, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtfiled_designation, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLbl8))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtfld_age, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtfld_lastname, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLbl13)
                                            .addComponent(jLabel4))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pass_box, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbl6)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl17)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLbl15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtfield_emailID, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLbl19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(lbl_nicno))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtFld_contactno, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(txtfld_nicno))))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jlbl6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfld_lastname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtfld_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLbll4)
                                .addComponent(jLabel1)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl5)
                            .addComponent(cmbbx_gender, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl8)
                            .addComponent(txtfld_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLbl7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtfld_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLbl13))
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl9)
                            .addComponent(jLabel4)
                            .addComponent(pass_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfiled_designation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl11, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfld_salary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLbl17)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLbl15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfield_emailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtFld_contactno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLbl19)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl_nicno, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtfld_nicno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_submit)
                            .addComponent(btn_reset))
                        .addGap(213, 213, 213))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbbx_genderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbbx_genderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbbx_genderActionPerformed

    private void txtfld_dobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld_dobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfld_dobActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        TxtFld_contactno.setText("");
        txtfield_emailID.setText("");
        txtfiled_designation.setText("");
        txtfld_age.setText("");
        txtfld_dob.setText("");
        txtfld_lastname.setText("");
        txtfld_name.setText("");
        txtfld_nicno.setText("");
        txtfld_salary.setText("");
        textArea_address.setText("");
        jDateChooser1.setDate(null);
        pass_box.setText("");
    }//GEN-LAST:event_btn_resetActionPerformed

    private void Btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_submitActionPerformed
        // TODO add your handling code here:
     Data dt=new Data();
     dt.Submit(txtfld_name.getText(), txtfld_lastname.getText(), textArea_address.getText(),txtfld_nicno.getText(), cmbbx_gender.getSelectedItem().toString() , pass_box.getText(), txtfld_age.getText(), txtfld_dob.getText(),jDateChooser1.getDateFormatString(), txtfld_salary.getText().toString(),txtfiled_designation.getText(), txtfield_emailID.getText(), TxtFld_contactno.getText());
        try {
            JOptionPane.showMessageDialog(null, "Thank you for submission");
        } catch (Exception e)
        {
          JOptionPane.showMessageDialog(null, e);  
        }
    }//GEN-LAST:event_Btn_submitActionPerformed

    private void txtfld_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld_nameActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtfld_nameActionPerformed

    private void TxtFld_contactnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFld_contactnoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TxtFld_contactnoActionPerformed

    private void txtfld_lastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld_lastnameActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtfld_lastnameActionPerformed

    private void txtfield_emailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfield_emailIDActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtfield_emailIDActionPerformed

    private void txtfld_salaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld_salaryActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtfld_salaryActionPerformed

    private void txtfld_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfld_ageActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtfld_ageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_submit;
    private javax.swing.JTextField TxtFld_contactno;
    private javax.swing.JButton btn_reset;
    private javax.swing.JComboBox<String> cmbbx_gender;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLbl1;
    private javax.swing.JLabel jLbl11;
    private javax.swing.JLabel jLbl13;
    private javax.swing.JLabel jLbl15;
    private javax.swing.JLabel jLbl16;
    private javax.swing.JLabel jLbl17;
    private javax.swing.JLabel jLbl19;
    private javax.swing.JLabel jLbl5;
    private javax.swing.JLabel jLbl7;
    private javax.swing.JLabel jLbl8;
    private javax.swing.JLabel jLbl9;
    private javax.swing.JLabel jLbll4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jlbl6;
    private javax.swing.JLabel lbl_nicno;
    private javax.swing.JPasswordField pass_box;
    private javax.swing.JTextArea textArea_address;
    private javax.swing.JTextField txtfield_emailID;
    private javax.swing.JTextField txtfiled_designation;
    private javax.swing.JTextField txtfld_age;
    private javax.swing.JTextField txtfld_dob;
    private javax.swing.JTextField txtfld_lastname;
    private javax.swing.JTextField txtfld_name;
    private javax.swing.JTextField txtfld_nicno;
    private javax.swing.JTextField txtfld_salary;
    // End of variables declaration//GEN-END:variables
}
