/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee_management_system;

import javax.swing.JOptionPane;

/**
 *
 * @author Afzal computers
 */
public class Leave_Form extends javax.swing.JFrame {

    /**
     * Creates new form Leave_Form
     */
    public Leave_Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lbl_empattendance = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        txt_Id = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        lbl_startdate = new javax.swing.JLabel();
        txt_Startdate = new javax.swing.JTextField();
        lbl_Enddate = new javax.swing.JLabel();
        txt_enddate = new javax.swing.JTextField();
        lbl_timein = new javax.swing.JLabel();
        txt_timein = new javax.swing.JTextField();
        lbl_timeout = new javax.swing.JLabel();
        txt_timeout = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_empname = new javax.swing.JLabel();
        txt_empname = new javax.swing.JTextField();
        btn_Enter = new javax.swing.JButton();
        lbl_leaves = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee_management_system/image001.png"))); // NOI18N

        lbl_empattendance.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lbl_empattendance.setText("Employee Attendance");

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Afzal computers\\Downloads\\e projects\\employee.png")); // NOI18N

        lbl_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_name.setText("Employee Name:");

        lbl_id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_id.setText("Employee ID:");

        txt_Id.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txt_name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lbl_startdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_startdate.setText("Start Date:");

        txt_Startdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lbl_Enddate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_Enddate.setText("End Date:");

        txt_enddate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_enddate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_enddateActionPerformed(evt);
            }
        });

        lbl_timein.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_timein.setText("Time In:");

        txt_timein.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lbl_timeout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_timeout.setText("Time Out:");

        txt_timeout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_timeout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_timeoutActionPerformed(evt);
            }
        });

        lbl_empname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_empname.setText("Employee Name:");

        txt_empname.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        btn_Enter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btn_Enter.setText("Enter");
        btn_Enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EnterActionPerformed(evt);
            }
        });

        lbl_leaves.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        lbl_leaves.setText("Apply Leave here");

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Submit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(lbl_empattendance)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(105, 105, 105)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btn_Enter)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbl_name)
                                                    .addComponent(lbl_timein))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_timein, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(60, 60, 60)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbl_timeout)
                                                    .addComponent(lbl_id))
                                                .addGap(34, 34, 34)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt_timeout, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_empname)
                                            .addComponent(lbl_startdate)
                                            .addComponent(lbl_Enddate))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_Startdate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_empname, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txt_enddate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(258, 258, 258)
                                                .addComponent(jButton1)))))
                                .addGap(0, 269, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(273, 273, 273)
                                        .addComponent(lbl_leaves)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lbl_empattendance)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_name)
                                    .addComponent(txt_Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_id)
                                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_timeout)
                                    .addComponent(txt_timeout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_timein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_timein))
                                .addGap(30, 30, 30)
                                .addComponent(btn_Enter)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_leaves)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_empname)
                                    .addComponent(txt_empname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_Startdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_startdate))
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_enddate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_Enddate)
                                    .addComponent(jButton1))))))
                .addContainerGap(113, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_timeoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_timeoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timeoutActionPerformed

    private void txt_enddateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_enddateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_enddateActionPerformed

    private void btn_EnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EnterActionPerformed
    
    try {
        Data dt=new Data();
    dt.Enter(txt_Id.getText(), txt_empname.getText(), txt_timein.getText(), txt_timeout.getText());
            JOptionPane.showMessageDialog(null, "Thank  You for Attendance");
        } catch (Exception e)
        {
          JOptionPane.showMessageDialog(null, e);  
        }
    }//GEN-LAST:event_btn_EnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Leave_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Leave_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Leave_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Leave_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Leave_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Enter;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl_Enddate;
    private javax.swing.JLabel lbl_empattendance;
    private javax.swing.JLabel lbl_empname;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_leaves;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_startdate;
    private javax.swing.JLabel lbl_timein;
    private javax.swing.JLabel lbl_timeout;
    private javax.swing.JTextField txt_Id;
    private javax.swing.JTextField txt_Startdate;
    private javax.swing.JTextField txt_empname;
    private javax.swing.JTextField txt_enddate;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_timein;
    private javax.swing.JTextField txt_timeout;
    // End of variables declaration//GEN-END:variables
}
